version: '2'

services:
  config-server:
    image: springcommunity/spring-petclinic-config-server
    container_name: config-server
    mem_limit: 512M
    entrypoint: ["java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9900
     - 8888:8888

  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9900
     - 8761:8761

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    mem_limit: 512M
    volumes:
     - ./docker/easeagent:/easeagent-volume
    depends_on:
     - config-server
     - discovery-server
    entrypoint: 
    - "./dockerize"
    - "-wait=tcp://discovery-server:8761"
    - "-timeout=60s"
    - "--"
    - "java"
    - "-javaagent:/easeagent-volume/easeagent-v2.0.1.jar" 
    - "-Deaseagent.server.port=9900"
    - "-Deaseagent.config.path=/easeagent-volume/agent-tempo.properties"
    - "-Deaseagent.name=consumer-service"
    - "org.springframework.boot.loader.JarLauncher"
    ports:
     - 9900
     - 8081:8081

  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    mem_limit: 512M
    volumes:
     - ./docker/easeagent:/easeagent-volume
    depends_on:
     - config-server
     - discovery-server
    entrypoint:
    - "./dockerize"
    - "-wait=tcp://discovery-server:8761"
    - "-timeout=60s"
    - "--"
    - "java"
    - "-javaagent:/easeagent-volume/easeagent-v2.0.1.jar" 
    - "-Deaseagent.server.port=9900"
    - "-Deaseagent.config.path=/easeagent-volume/agent-tempo.properties"
    - "-Deaseagent.log.conf=/easeagent-volume/easeagent-log4j2.xml"
    - "-Deaseagent.name=visits-service"
    - "org.springframework.boot.loader.JarLauncher"
    ports:
     - 9900
     - 8082:8082

  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    mem_limit: 512M
    volumes:
     - ./docker/easeagent:/easeagent-volume
    depends_on:
     - config-server
     - discovery-server
    entrypoint: 
    - "./dockerize"
    - "-wait=tcp://discovery-server:8761"
    - "-timeout=60s"
    - "--"
    - "java"
    - "-javaagent:/easeagent-volume/easeagent-v2.0.1.jar" 
    - "-Deaseagent.server.port=9900"
    - "-Deaseagent.config.path=/easeagent-volume/agent-tempo.properties"
    - "-Deaseagent.log.conf=/easeagent-volume/easeagent-log4j2.xml"
    - "-Deaseagent.name=vets-service"
    - "org.springframework.boot.loader.JarLauncher"
    ports:
     - 9900
     - 8083:8083

  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    volumes:
     - ./docker/easeagent:/easeagent-volume
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: 
    - "./dockerize"
    - "-wait=tcp://discovery-server:8761"
    - "-timeout=60s"
    - "--"
    - "java"
    - "-javaagent:/easeagent-volume/easeagent-v2.0.1.jar" 
    - "-Deaseagent.server.port=9900"
    - "-Deaseagent.config.path=/easeagent-volume/agent-tempo.properties"
    - "-Deaseagent.log.conf=/easeagent-volume/easeagent-log4j2.xml"
    - "-Deaseagent.name=api-gateway"
    - "org.springframework.boot.loader.JarLauncher"
    ports:
     - 9900
     - 8080:8080

  admin-server:
    image: springcommunity/spring-petclinic-admin-server
    container_name: admin-server
    volumes:
     - ./docker/easeagent:/easeagent-volume
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9090:9090


  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo-local.yaml:/etc/tempo.yaml
      - ./docker/tempo/overrides.yaml:/etc/overrides.yaml
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200"   # tempo
      - "9411:9411"   # zipkin

  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    volumes:
      - ./docker/load-generator.json:/etc/load-generator.json
    environment:
      - TOPOLOGY_FILE=/etc/load-generator.json
      - ZIPKINV2_JSON_URL=http://tempo:9411
    depends_on:
      - tempo

  prometheus:
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus.yaml" ]
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:main
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
